# Generated by Django 5.0.2 on 2024-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(max_length=400),
        ),
    ]
