# Generated by Django 5.0.2 on 2024-02-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('about_us_description', models.TextField()),
                ('image', models.ImageField(upload_to='about_us/title_section_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_role_name', models.CharField(max_length=100)),
                ('executive_role_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('title_image', models.ImageField(upload_to='home_title_image/')),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_application_form_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', models.CharField(max_length=200)),
                ('join_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.joinus')),
            ],
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_heading', models.TextField()),
                ('mission_subheading', models.TextField()),
                ('mission_image', models.ImageField(upload_to='mission_image/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.home')),
            ],
        ),
        migrations.CreateModel(
            name='OpenRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_form_link', models.CharField(max_length=500)),
                ('open_roles', models.TextField()),
                ('join_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.joinus')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='programs/images/')),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.programs')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_name', models.CharField(max_length=100)),
                ('progress_stat', models.CharField(max_length=100)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('roles_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('join_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.joinus')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_logo', models.ImageField(upload_to='about_us/sponsor_section_logos/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_management_role_name', models.CharField(max_length=100)),
                ('website_management_role_description', models.TextField()),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.roles')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AddField(
            model_name='executive',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.roles'),
        ),
    ]
