# Generated by Django 5.0.2 on 2024-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutus_executive_home_joinus_membershipbenefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='executive_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roles',
            name='exeuctive_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='roles',
            name='website_management_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roles',
            name='website_management_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
