# Generated by Django 5.0.2 on 2024-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_roles_executive_description_roles_exeuctive_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='executive_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roles',
            name='exeuctive_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roles',
            name='website_management_title',
            field=models.CharField(max_length=200),
        ),
    ]
