# Generated by Django 5.0.2 on 2024-02-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_roles_executive_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='exeuctive_title',
            new_name='executive_title',
        ),
    ]
