# Generated by Django 5.0.2 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_exeuctive_title_roles_executive_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
