# Generated by Django 5.0.2 on 2024-02-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_home_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='footer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
