# Generated by Django 5.0.2 on 2024-02-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_home_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorInformationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aboutus')),
            ],
        ),
    ]
