# Generated by Django 5.0.2 on 2024-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_home_github_link_home_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='about_us/title_section_images/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_image',
            field=models.ImageField(upload_to='home/title_image/'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='mission_image',
            field=models.ImageField(upload_to='home/mission_image/'),
        ),
        migrations.AlterField(
            model_name='programssections',
            name='image',
            field=models.ImageField(upload_to='programs/images/'),
        ),
        migrations.AlterField(
            model_name='sponsorsection',
            name='sponsor_logo',
            field=models.ImageField(upload_to='about_us/sponsor_section_logos/'),
        ),
    ]
