# Generated by Django 5.0.3 on 2024-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_partners_alter_home_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AlterField(
            model_name='home',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='media/logo'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_image',
            field=models.ImageField(upload_to='media/home/title_image/'),
        ),
    ]
