# Generated by Django 5.0.3 on 2024-03-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_aboutus_subtitle_remove_aboutus_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='title',
        ),
    ]
