# Generated by Django 5.0.3 on 2024-03-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_roles_subtitle_remove_roles_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='executive_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='executive_title',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='roles_description',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='website_management_description',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='website_management_title',
        ),
    ]
