# Generated by Django 5.0.3 on 2024-03-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_rename_executive_description_roles_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='title',
        ),
    ]
